name: FastAPI CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          source $HOME/.cargo/env
          uv sync --group lint

      - name: Run Black
        run: |
          source $HOME/.cargo/env
          uv run black --check .

      - name: Run Isort
        run: |
          source $HOME/.cargo/env
          uv run isort --check-only .

      - name: Run Flake8
        run: |
          source $HOME/.cargo/env
          uv run flake8 . --max-line-length=119

      - name: Run Mypy
        run: |
          source $HOME/.cargo/env
          uv run mypy .
